version: '3'
services:
  rabbitmq:
    image: "rabbitmq:management" 
    ports:
      - "5672:5672" 
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: "chat_app"
      RABBITMQ_DEFAULT_PASS: "chat_app_password"
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq 

networks:
  default:
    driver: bridge
